{{- if .Values.customChainsConfig.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.customChainsConfig.name }}
  namespace: {{ default .Release.Namespace .Values.namespaceOverride | quote }}
  labels:
    {{- include "cvms.labels" . | nindent 4 }}
    {{- with .Values.customChainsConfig.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.customChainsConfig.annotations }}
  annotations:
    {{ toYaml .Values.customChainsConfig.annotations | indent 4 }}
  {{- end }}
data:
  custom_chains.yaml.example: |
    {{- .Files.Get "files/custom_chains.yaml.example" | nindent 4 }}
{{- end }}