{{- if and .Values.exporter.serviceMonitor.enabled .Values.exporter.serviceMonitor.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "cvms.labels" . | nindent 4 }}
    {{- include "cvms.exporterSelectorMetricLabels" . | nindent 4 }}
    {{- with .Values.exporter.metrics.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.exporter.serviceMonitor.prometheusRule.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.exporter.serviceMonitor.prometheusRule.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "cvms.fullname" . }}
  namespace: {{ coalesce .Values.exporter.serviceMonitor.prometheusRule.namespace .Values.exporter.serviceMonitor.namespace .Release.Namespace | quote }}
spec:
  groups:
{{- $files := .Files }}
{{- range .Values.exporter.serviceMonitor.prometheusRule.ruleSets }}
  {{- if .enabled }}
    {{- $filePath := printf "files/%s.yaml" .name }}
    {{- $fileContent := $files.Get $filePath | default "" }}
    {{- if $fileContent }}
      {{- $parsedYaml := fromYaml $fileContent }}
      {{- range $parsedYaml.groups }}
    - name: {{ .name }}
      rules:
      {{- toYaml .rules | nindent 8 }}
      {{- end }}
    {{- else }}
      {{ printf "Warning: File %s not found or empty" $filePath | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
  {{- if .Values.exporter.serviceMonitor.prometheusRule.rules }}
    - name: {{ include "cvms.fullname" . }}
      rules: {{- toYaml .Values.exporter.serviceMonitor.prometheusRule.rules | nindent 8 }}
  {{- end }}
{{- end }}