{
 "title": "Validator Trend Dashboard",
 "description": "sample validator dashboard",
 "tags": [
  "balance",
  "upgrade",
  "axelarevm",
  "yoda",
  "oracle",
  "eventnonce",
  "uptime",
  "block"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<!-- Main content -->\n<div style=\"display: flex; justify-content: space-between; align-items: center;\">\n  <!-- H2 with a link -->\n   <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n    <h2 style=\"margin-right: 10px;\">Cosmos Validator Monitoring Service (CVMS) 🌌 🔭</h2>\n  </a> \n  <!-- \"Powered by Cosmostation\" on the right -->\n  <div style=\"display: flex; align-items: center;\">\n    <a href=\"https://cosmostation.io\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n        <span>Powered by Cosmostation </span>\n        <img src=\"https://raw.githubusercontent.com/cosmostation/chainlist/refs/heads/main/resource/cosmostation/cosmostation_color.svg\" alt=\"Logo\" style=\"height: 30px; margin-left: 5px;\">\n    </a>\n  </div>\n</div>\n\n<!-- Paragraph below the header -->\n<p>\n  The Cosmos Validator Monitoring Service (CVMS) is an open-source, integrated monitoring system designed for validators and network in the Cosmos app chain ecosystem.<br/>\n  This public dashboard is part of the beta launch, with the open-source repository coming soon.\n</p>\n<p>\n  <a href=\"https://public-cosmos-vms.cosmostation.io/d/be37h6ce99dz4e/network-duty-dashboard?from=now-30m\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 Validator Duty Overview Click Here\n  </a> \n  <a href=\"https://public-cosmos-vms.cosmostation.io\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 Validator Consensus Overview Click Here\n  </a> \n</p>"
   }
  },
  {
   "title": "Validator Golden Timer",
   "type": "table",
   "description": "The golden time means you should recover back up in consensus in specific duration. if not, your validator node will be jailed by onchain parameter ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ceil(cvms_uptime_signed_blocks_window * (1 - cvms_uptime_min_signed_per_window)) - on (chain_id) group_right () cvms_uptime_missed_blocks_counter) without (proposer_address, validator_consensus_address, validator_operator_address, instance, job, package, service)\n* on (chain_id) group_left () min by (chain_id) (60*60 / delta(cvms_block_height[1h]))"
    }
   ]
  },
  { "title": "Validator Utilies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Onchain Upgrade Timer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cvms_upgrade_remaining_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Remaining Balances For Tracking Addresses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cvms_balance_remaining_amount", "legendFormat": "__auto" }
   ]
  },
  { "title": "Validator Duties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Network Highest Eventnonce Value",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cvms_eventnonce_highest_nonce) without (job, instance, package)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Eventnonce Value",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cvms_eventnonce_nonce) without (job, instance, package)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Eventnonce Difference Value",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 21 },
   "targets": [
    {
     "expr": "sum(cvms_eventnonce_highest_nonce - on (chain) group_right cvms_eventnonce_nonce) without (job, instance, package)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oracle Vote Window",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cvms_oracle_vote_window", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Oracle MissCounter",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cvms_oracle_miss_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Oracle Slashing Threshold",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 7, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cvms_oracle_min_valid_per_window",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oracle Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum((cvms_oracle_vote_window - on (chain_id) group_right cvms_oracle_miss_counter) / on(chain_id) group_left cvms_oracle_vote_window) without (job, instance, package)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yoda Status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cvms_yoda_status) without (validator_operator_address, instance, job, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Axelar EVM Activated Chains",
   "type": "stat",
   "gridPos": { "h": 12, "w": 9, "x": 3, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cvms_axelar_evm_activated_chain) without (instance, job, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Axelar EVM Maintainer Status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cvms_axelar_evm_maintainer_status) without (instance, job, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Validator Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Validator Uptime Trend",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round((1 - sum(cvms_uptime_missed_blocks_counter{mainnet=\"true\"}) without (instance, job, package, validator_consensus_address, validator_operator_address, proposer_address) / on (chain_id) group_left cvms_uptime_signed_blocks_window) * 100, 0.01)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Healths", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Node Timestamp Sync Status",
   "type": "stat",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sum(cvms_block_timestamp) without (instance, job, package)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}