{
 "title": "Axelar Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cvms_block_timestamp,table_chain_id)"
    }
   },
   {
    "name": "chain",
    "label": "Chain",
    "query": {
     "query": "label_values(cvms_block_timestamp{table_chain_id=\"$chain_id\"},chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<!-- Main content -->\n<div style=\"display: flex; justify-content: space-between; align-items: center;\">\n  <!-- H2 with a link -->\n   <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n    <h2 style=\"margin-right: 10px;\">Cosmos Validator Monitoring Service (CVMS) 🌌 🔭</h2>\n  </a> \n  <!-- \"Powered by Cosmostation\" on the right -->\n  <div style=\"display: flex; align-items: center;\">\n    <a href=\"https://cosmostation.io\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n        <span>Powered by Cosmostation </span>\n        <img src=\"https://raw.githubusercontent.com/cosmostation/chainlist/refs/heads/main/resource/cosmostation/cosmostation_color.svg\" alt=\"Logo\" style=\"height: 30px; margin-left: 5px;\">\n    </a>\n  </div>\n</div>\n\n<!-- Paragraph below the header -->\n<p>\n  The Cosmos Validator Monitoring Service (CVMS) is an open-source, integrated monitoring system designed for validators and network in the Cosmos app chain ecosystem.<br/>\n  This public dashboard is a playground for developers and beta release testing for CVMS.\n</p>\n<p>\n  <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 CVMS Github Link Here!\n  </a> \n  <a href=\"https://github.com/cosmostation/cvms/blob/release/docs/setup.md\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 CVMS Setup Guide Here!!\n  </a> \n</p>"
   }
  },
  {
   "title": "Amplifier Verifier Indexed Vote Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "\n\t\tSELECT vi.moniker,\n\t\tCOUNT(CASE WHEN status = 0 THEN 1 END) as \"DidNotVote\",\n\t\tCOUNT(CASE WHEN status = 1 THEN 1 END) as \"FailedOnChain\",\n\t\tCOUNT(CASE WHEN status = 2 THEN 1 END) as \"NotFound\",\n\t\tCOUNT(CASE WHEN status = 3 THEN 1 END) as \"SucceededOnChain\"\n\tFROM axelar_amplifier_verifier_${chain_id} idx\n\tJOIN meta.verifier_info vi ON idx.verifier_id  = vi.id\n\tWHERE idx.created_at < NOW() + INTERVAL '1 minutes'\n\tGROUP BY vi.moniker;"
    }
   ]
  },
  {
   "title": "Amplifier Verifier Failed Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "rawSql": "\nSELECT \n  vi.moniker,\n  idx.chain_and_poll_id\nFROM axelar_amplifier_verifier_${chain_id} idx\nJOIN meta.verifier_info vi ON idx.verifier_id  = vi.id\nWHERE idx.status  != 3"
    }
   ]
  },
  {
   "title": "Amplifier Verifier Vote Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 38, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "\nSELECT\n  t1.poll_start_height,\n  t2.verifier_address,\n  t1.status,\n  t1.chain_and_poll_id,\n  t1.poll_vote_height\nFROM\n  axelar_amplifier_verifier_${chain_id} t1\nJOIN\n  meta.verifier_info t2\n  ON t1.verifier_id = t2.id"
    }
   ]
  }
 ]
}