{
 "title": "Babylon Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cvms_block_timestamp,table_chain_id)"
    }
   },
   {
    "name": "chain",
    "label": "Chain",
    "query": {
     "query": "label_values(cvms_block_timestamp{table_chain_id=\"$chain_id\"},chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<!-- Main content -->\n<div style=\"display: flex; justify-content: space-between; align-items: center;\">\n  <!-- H2 with a link -->\n   <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n    <h2 style=\"margin-right: 10px;\">Cosmos Validator Monitoring Service (CVMS) 🌌 🔭</h2>\n  </a> \n  <!-- \"Powered by Cosmostation\" on the right -->\n  <div style=\"display: flex; align-items: center;\">\n    <a href=\"https://cosmostation.io\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n        <span>Powered by Cosmostation </span>\n        <img src=\"https://raw.githubusercontent.com/cosmostation/chainlist/refs/heads/main/resource/cosmostation/cosmostation_color.svg\" alt=\"Logo\" style=\"height: 30px; margin-left: 5px;\">\n    </a>\n  </div>\n</div>\n\n<!-- Paragraph below the header -->\n<p>\n  The Cosmos Validator Monitoring Service (CVMS) is an open-source, integrated monitoring system designed for validators and network in the Cosmos app chain ecosystem.<br/>\n  This public dashboard is a playground for developers and beta release testing for CVMS.\n</p>\n<p>\n  <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 CVMS Github Link Here!\n  </a> \n  <a href=\"https://github.com/cosmostation/cvms/blob/release/docs/setup.md\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 CVMS Setup Guide Here!!\n  </a> \n</p>"
   }
  },
  { "title": "Babylon Third Party Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "BTC LightClient Reporter Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": ";  -- Order in ascending order for the last 100 blocks\nWITH max_height AS (\n  SELECT MAX(height) AS highest_height\n  FROM babylon_btc_lightclient_${chain_id}\n)\nSELECT\n  bbl.height, -- height, header_count, btc_headers.\n  bbl.header_count,\n  vi.operator_address as address,\n  bbl.btc_headers\nFROM\n  babylon_btc_lightclient_${chain_id} bbl\nJOIN\n  meta.validator_info vi\n  ON bbl.reporter_id = vi.id\nJOIN\n  max_height mh  -- Join to get the maximum block height\n  ON bbl.height BETWEEN (mh.highest_height - 1000) AND mh.highest_height\nORDER BY height asc"
    }
   ]
  },
  {
   "title": "Covenant Signing State",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "WITH latest_delegations AS (\n    SELECT * \n    FROM public.babylon_btc_delegation \n    ORDER BY height DESC\n    LIMIT 100\n)\nSELECT \n    ld.chain_info_id,\n    ld.height AS delegation_height,\n    ld.btc_staking_tx_hash,\n    COALESCE(bcs.height, -1) AS signature_height,  \n    COALESCE(bcs.covenant_btc_pk_id, cci.id) AS covenant_btc_pk_id,\n    COALESCE(cci.covenant_btc_pk, 'N/A') AS covenant_btc_pk,\n    CASE \n        WHEN bcs.btc_staking_tx_hash IS NOT NULL AND cci.id IS NOT NULL THEN TRUE\n        ELSE FALSE\n    END AS status\nFROM latest_delegations ld\nCROSS JOIN meta.covenant_committee_info cci \nLEFT JOIN public.babylon_covenant_signature bcs \n    ON ld.btc_staking_tx_hash = bcs.btc_staking_tx_hash\n    AND ld.chain_info_id = bcs.chain_info_id\n    AND cci.id = bcs.covenant_btc_pk_id\nWHERE ld.chain_info_id = cci.chain_info_id\nORDER BY ld.height DESC, cci.id;"
    }
   ]
  },
  { "title": "Finality Provider Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Finality Provider Vote Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 34, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": ";  -- Order in ascending order for the last 100 blocks\nWITH max_height AS (\n  SELECT MAX(height) AS highest_height\n  FROM babylon_finality_provider_${chain_id}\n)\nSELECT\n  bfp.height,\n  bfp.status,\n  fpi.moniker AS moniker,\n  fpi.operator_address as address,\n  fpi.btc_pk as btc_pk\nFROM\n  babylon_finality_provider_${chain_id} bfp\nJOIN\n  meta.finality_provider_info fpi\n  ON bfp.finality_provider_pk_id = fpi.id\nJOIN\n  max_height mh  -- Join to get the maximum block height\n  ON bfp.height BETWEEN (mh.highest_height - 50) AND mh.highest_height\nORDER by\n  bfp.height ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Finality Provider Uptime Trend",
   "type": "timeseries",
   "gridPos": { "h": 34, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(1 - cvms_finality_provider_missed_votes_counter / on (chain_id) group_left cvms_finality_provider_signed_votes_window, 0.001) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Validator Signing Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Consensus Vote Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 40, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": ";  -- Order in ascending order for the last 100 blocks\nWITH max_height AS (\n  SELECT MAX(height) AS highest_height\n  FROM voteindexer_${chain_id}\n)\nSELECT\n  vidx.height,\n  vidx.status,\n  vi.moniker AS moniker\nFROM\n  voteindexer_${chain_id} vidx\nJOIN\n  meta.validator_info vi\n  ON vidx.validator_hex_address_id = vi.id\nJOIN\n  max_height mh  -- Join to get the maximum block height\n  ON vidx.height BETWEEN (mh.highest_height - 50) AND mh.highest_height\nORDER by\n  vidx.height ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Checkpoint BLS Vote Status",
   "type": "nline-plotlyjs-panel",
   "description": "Extension Vote means ABCI++(2.0) feature.",
   "gridPos": { "h": 40, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "rawSql": "WITH epoch AS (\n  SELECT MAX(epoch) as max_epoch FROM babylon_checkpoint_${chain_id}\n)\n select\n  idx.height,\n  idx.status,\n  vi.moniker AS moniker,\n  idx.epoch\nFROM\n  babylon_checkpoint_${chain_id} idx\nJOIN\n  meta.validator_info vi\n  ON idx.validator_hex_address_id = vi.id\nJOIN\n  epoch\n  ON idx.epoch BETWEEN (epoch.max_epoch - 30) AND epoch.max_epoch\nORDER by\n  idx.height DESC\n"
    }
   ]
  }
 ]
}