groups:
  - name: AxelarEVMPackage
    rules:
      - alert: AxelarEVMChainMaintainerInactive
        expr: cvms_axelar_evm_maintainer_status == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: 'Axelar EVM Maintainer for `{{ $labels.evm_chain }}` is inactive in {{ $labels.chain_id }}'

  - name: AxelarAmplifierVerifierPackage
    rules:
      - alert: AmplifierVerifierFailedVoting
        expr: cvms_axelar_amplifier_verifier_poll_vote{status!~"SucceededOnChain"} - (cvms_axelar_amplifier_verifier_poll_vote offset 10m) > 0
        labels:
          severity: warning
        annotations:
          summary: 'Axelar Amplifier Verifer Missed vote in {{ $labels.chain_id }}'
          description: |
            In {{ $labels.chain_id }}, {{ $labels.verifier }} did not vote for some chains. 
            Check it now <https://public-cvms.cosmostation.io/d/axelar_dashboard/axelar-dashboard|here>
  
  - name: AxelarValdHeartbeatsPackage
    rules:
      - alert: AxelarValdHeartbeatsStopped
        expr: group by (chain_id, broadcastor_address, moniker, validator_operator_address, mainnet) (increase(cvms_axelar_vald_heartbeats_count_total{status="missed"}[15m])) > 2
        labels:
          severity: warning
        annotations:
          summary: 'Axelar Vald heartbeat has stopped for {{ $labels.moniker }} in {{ $labels.chain_id }}.'
